server.servlet.context-path: /challenge
spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: challenge
  jpa:
    database: postgresql
  flyway:
    baseline-on-migrate: true